del smic.inf
del smic.exe
clipper smic /w > livecomp.aaa
clipper enqmenu /w >> livecomp.aaa
clipper prntmenu /w >> livecomp.aaa
clipper etadmin /w >> livecomp.aaa
clipper repmenu /w >> livecomp.aaa
clipper datamenu /w >> livecomp.aaa
clipper accmenu /w >> livecomp.aaa
clipper accsubmn /w >> livecomp.aaa
clipper stdmenu /w >> livecomp.aaa
clipper ldmenu /w >> livecomp.aaa
clipper medmenu /w >> livecomp.aaa
clipper advmenu /w >> livecomp.aaa
clipper twin /w >> livecomp.aaa
clipper stdpmenu /w >> livecomp.aaa
clipper crs1 /w >> livecomp.aaa
clipper crs3 /w >> livecomp.aaa
rtlink @smiclive >> livecomp.aaa
copy smic.exe c:\db\smic\live